### ISSUE TITLE
Create UX wireframes

### ISSUE THREAD

**Issue by richardhallett** [datacite/beagle#16]
To describe how the web application will functionally look.

Screens required:

All
* Navigation

Home
* Text description of the PID services registry
* Services Search Listing
* Free text search query input

Search results showing basic service information
* Service Name
* Service Description
* Organisation Name
* Filters displayed to refine search

Service Details
* Detail of service
* Service Name
* Service Description
* Organisation Name
* URL

**Comment by pamfilos** [comment]
https://www.figma.com/file/04BKdrSNjAPsTJXZ8GzxV1/beagle?node-id=0%3A1

**Comment by richardhallett** [comment]
@pamfilos Those look great.
I was thinking for the homepage, maybe we should consider like what the EOSC marketplace has in terms of discipline/categories? https://marketplace.eosc-portal.eu/

So rather than listing services, we instead have categories that link through to relevant filtered list.

Could you perhaps mock that up in a wireframe? I leave it up to you how we might display this, but that's general idea.

**Comment by richardhallett** [comment]
Decided to just have filters on main search page and remove homepage. No need for extra work here.
Closing as wireframes we have are sufficient.
